package Oops.Abstract_Classes_And_Methods;

public abstract class Parent {
    abstract void caarer();
    abstract void Exp ();
}

//A CLASS WHICH CONTAINS ONE OR MORE ABSTRACT METHODS SHOULD BE DECLARED AS ABSTRACT CLASS.
//ABSTRACT METHODS ARE INITIATED IN ABSTRACT CLASS AND THEN OVERRIDEN IN CHILD CLASS.
//ABSTRACT CONSTRUCTORS AND ABSTRACT STATIC METHODS ARE NOT ALLOWED.